In [141]:
# Sentiment Analysis on IMDb Reviews

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report, accuracy_score,confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder

In [142]:
# 1. Load dataset
df = pd.read_csv("IMDB Dataset.csv")
df.head(-1)

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49994  This is your typical junk comedy.<br /><br />T...  negative
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative

[49999 rows x 2 columns]

In [143]:
df.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [144]:
df.isna().sum()

review       0
sentiment    0
dtype: int64

In [145]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [146]:
# 2. Split data into train and test
x = df['review']
y = df['sentiment'].map({'positive':1, 'negative':0})  # convert labels to 0/1

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

In [147]:
# lable=LabelEncoder()
# df['sentiment_encoded']=lable.fit_transform(df['sentiment'])

In [148]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 50000, dtype: int64

In [149]:
# le=LabelEncoder()
# df['sentiment_labled']=le.fit_transform(df['sentiment'])

In [150]:
# df['sentiment'].iloc[22]

In [151]:
pipe_svm= Pipeline([
    ("tfidf", TfidfVectorizer(stop_words='english',max_features=20000, ngram_range=(1,2), min_df=2)),
    ("model", LinearSVC(C=0.3,loss='squared_hinge',class_weight=None,dual=False,max_iter=5000))
    ])
#زمانی که تعداد فیچر هامون بیشتر از سمپل باشه =True تاثیر اینکار روی سرعت پردازشه روی داده تغییر خاصی اعمال نمیکنه

In [152]:
pipe_log= Pipeline([
    ("tfidf", TfidfVectorizer(stop_words='english',max_features=20000, ngram_range=(1,2), min_df=5)),
    ("bot", LogisticRegression(max_iter=200))
])

In [153]:
# 3. Text preprocessing + feature extraction (TF-IDF)
# vectorizer = TfidfVectorizer(stop_words='english', max_features=20000,ngram_range=(1,2)) # limit features for simplicity+ ngram(1,2)

# X_train_tfidf = vectorizer.fit_transform(X_train)
# X_test_tfidf = vectorizer.transform(X_test)

In [154]:
# X_train_tfidf.shape

In [155]:
# 4. Train a simple ML model

pipe_log.fit(X_train, y_train)

pipe_svm.fit(X_train,y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_features=20000, min_df=2,
                                 ngram_range=(1, 2), stop_words='english')),
                ('model', LinearSVC(C=0.3, dual=False, max_iter=5000))])

In [156]:
# 5. Evaluate model
y_pred_log= pipe_log.predict(X_test)
y_pred_svm=pipe_svm.predict(X_test)

In [162]:
# 6. Try a custom review
sample_review = "i hate that"
# sample_vec = vectorizer.transform([sample_review])
prediction = pipe_log.predict([sample_review])[0]
if prediction==1:
    print("\npositive")
elif prediction!=1:
    print("Negetive")

positive

In [158]:
sample_review = "that was terrible"
# sample_vec = vectorizer.transform([sample_review])
prediction = pipe_svm.predict([sample_review])[0]
if prediction==1:
    print("\npositive")
else:
    print("Negetive")

Negetive

In [159]:
print("\nModel Performance:")
print("Accuracy:", accuracy_score(y_test, y_pred_log))
print("\nClassification Report:\n", classification_report(y_test, y_pred_log))

Model Performance:
Accuracy: 0.9001

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.89      0.90      5000
           1       0.89      0.91      0.90      5000

    accuracy                           0.90     10000
   macro avg       0.90      0.90      0.90     10000
weighted avg       0.90      0.90      0.90     10000

In [160]:
print("\nModel Performance:")
print("Accuracy:", accuracy_score(y_test, y_pred_svm))
print("\nClassification Report:\n", classification_report(y_test, y_pred_svm))

Model Performance:
Accuracy: 0.9052

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.90      0.90      5000
           1       0.90      0.91      0.91      5000

    accuracy                           0.91     10000
   macro avg       0.91      0.91      0.91     10000
weighted avg       0.91      0.91      0.91     10000

In [161]:
confusion=confusion_matrix(y_test,y_pred_svm)
print(confusion)

[[4488  512]
 [ 436 4564]]